export const DataSource = [
  {
    key: "1",
    id: "01",
    tenantName: "John Smith",
    companyName: "Bills plumbing",
    issue: "Leaky kitchen sink",
    status: "Contacted",
    date: "21/04/24",
    time: "11:32 AM",
  },
  {
    key: "2",
    id: "02",
    tenantName: "Wade Warren",
    companyName: "Estep electric",
    issue: "Bedroom lights flickering",
    status: "Pending",
    date: "18/03/24",
    time: "10:02 AM",
  },
  {
    key: "3",
    id: "03",
    tenantName: "Jenny Wilson",
    companyName: "Bills plumbing",
    issue: "Clogged toilet",
    status: "Waiting",
    date: "02/03/24",
    time: "09:02 AM",
  },
  {
    key: "4",
    id: "04",
    tenantName: "Guy Hawkins",
    companyName: "Air leaks",
    issue: "Cracked window pane",
    status: "Contacted",
    date: "24/02/24",
    time: "10:02 AM",
  },
  {
    key: "5",
    id: "05",
    tenantName: "Robert Fox",
    companyName: "Bills plumbing",
    issue: "Water heater not heating",
    status: "Contacted",
    date: "22/02/24",
    time: "08:32 AM",
  },
  {
    key: "6",
    id: "06",
    tenantName: "Eleanor Pena",
    companyName: "Estep electric",
    issue: "Faulty electrical outlet",
    status: "Pending",
    date: "25/02/24",
    time: "12:32 AM",
  },
];

export const DataSource2 = [
  {
    key: "1",
    id: "#3435",
    tenantName: "John Doe",
    time: "10",
  },
  {
    key: "2",
    id: "#4567",
    tenantName: "Jane Smith",
    time: "11",
  },
  {
    key: "3",
    id: "#7890",
    tenantName: "Michael Johnson",
    time: "12",
  },
  {
    key: "4",
    id: "#1234",
    tenantName: "Emily Brown",
    time: "1",
  },
  {
    key: "5",
    id: "#5678",
    tenantName: "William Taylor",
    time: "2",
  },
  {
    key: "6",
    id: "#9012",
    tenantName: "Olivia Martinez",
    time: "3",
  },
  {
    key: "7",
    id: "#3456",
    tenantName: "James Anderson",
    time: "4",
  },
  {
    key: "8",
    id: "#7891",
    tenantName: "Sophia Thomas",
    time: "5",
  },
  {
    key: "9",
    id: "#2345",
    tenantName: "David Wilson",
    time: "6",
  },
  {
    key: "10",
    id: "#6789",
    tenantName: "Emma Garcia",
    time: "7",
  },
  {
    key: "11",
    id: "#1235",
    tenantName: "Daniel Martinez",
    time: "8",
  },
  {
    key: "12",
    id: "#5679",
    tenantName: "Isabella Hernandez",
    time: "9",
  },
  {
    key: "13",
    id: "#9013",
    tenantName: "Alexander Wright",
    time: "10",
  },
  {
    key: "14",
    id: "#3457",
    tenantName: "Ava King",
    time: "11",
  },
  {
    key: "15",
    id: "#7892",
    tenantName: "Mia Lewis",
    time: "12",
  },
];

export const dataSource3 = [
  {
    key: "1",
    id: "001",
    name: "John Doe",
    address: "123 Main St",
    phone: "123-456-7890",
    rent: "$1000",
  },
  {
    key: "2",
    id: "002",
    name: "Jane Smith",
    address: "456 Elm St",
    phone: "987-654-3210",
    rent: "$1200",
  },
  {
    key: "3",
    id: "003",
    name: "Alice Johnson",
    address: "789 Oak St",
    phone: "111-222-3333",
    rent: "$800",
  },
  {
    key: "4",
    id: "004",
    name: "Bob Brown",
    address: "321 Pine St",
    phone: "444-555-6666",
    rent: "$1100",
  },
  {
    key: "5",
    id: "005",
    name: "Emily Davis",
    address: "567 Maple St",
    phone: "777-888-9999",
    rent: "$950",
  },
  {
    key: "6",
    id: "006",
    name: "Michael Wilson",
    address: "901 Cedar St",
    phone: "222-333-4444",
    rent: "$1050",
  },
  {
    key: "7",
    id: "007",
    name: "Sarah Taylor",
    address: "234 Birch St",
    phone: "555-666-7777",
    rent: "$850",
  },
  {
    key: "8",
    id: "008",
    name: "David Martinez",
    address: "876 Spruce St",
    phone: "888-999-0000",
    rent: "$1250",
  },
  {
    key: "9",
    id: "009",
    name: "Laura Rodriguez",
    address: "543 Cedar St",
    phone: "333-444-5555",
    rent: "$900",
  },
  {
    key: "10",
    id: "010",
    name: "William Garcia",
    address: "987 Pine St",
    phone: "666-777-8888",
    rent: "$1150",
  },
];
